const types = {
  SET_DATA_RESERVATION: 'SET_DATA_RESERVATION',

  TOGGLE_MODAL_SELECT_TYPE_RESERVATION: 'TOGGLE_MODAL_SELECT_TYPE_RESERVATION',
  TOGGLE_MODAL_RESERVE_WITH_USER: 'TOGGLE_MODAL_RESERVE_WITH_USER',
  TOGGLE_MODAL_REGISTER_USER: 'TOGGLE_MODAL_REGISTER_USER',

  TOGGLE_MODAL_SUCCESS: 'TOGGLE_MODAL_SUCCESS',
  TOGGLE_MODAL_ERROR: 'TOGGLE_MODAL_ERROR',
};

export default types;
